blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://fabulously-optimized.github.io/discord
    about: General questions and support will be provided on the modpack's Discord
