name = "Fabulously Optimized"
author = "robotkoer"
version = "5.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31099c4e56e47800df166d8deb75167678190eb64d863ff97234d7d296e11bd3"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
