name = "Fabulously Optimized"
author = "robotkoer"
version = "4.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67d1da8535dd16fa67871c84492a03993f005c74902847390393e2413559322d"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
